### ISSUE TITLE
Authenticate Minecraft accounts

### ISSUE THREAD

**Issue by jengel3** [mc-extras/SpongeDev#12]
[Previous discussion](https://github.com/Jake0oo0/Spongy/commit/dc7320af4daec07cd4662d24a7b03a9c8af5a2ed#commitcomment-8186923)

---

So there basically needs to be a way to get authenticate Minecraft accounts so that skins can be verified and displayed with minotaur. This could be accomplished in basically two ways:

1) Username & Password - Unsafe and would generally steer people away from authenticating their account.

2) Verification Server - This would be as simple as having a MC server that a player can join and get a authentication token. This wouldn't be possible as of now due to fund limitations, but if this is ever actually used for anything, it could be fairly simple to set up.

For now, it will probably be best to leave method 1 as it is, and warn people that their credentials are always safe, but account confirmation is not necessary if they do not feel the need to. 

A third option of providing a verification skin is also possible, but requires a fair bit of extra implementation, and could be considered for a third method, but likely not necessary. This could though be of advantage to people who do not currently have access to a computer that can play Minecraft, or do not want to enter their login information.

**Comment by jomo** [comment]
I'm wondering how hard it would be to write a server that only does the auth and token stuff, without any other code for gameplay, considering that your average MC server needs a fair amount of resources.

The skin auth would actually be fairly simple to implement server-wise, but it's an extra step for the user and very 'unclean'.

PS: it's called minotar, not minotaur (think Minecraft/avatar)

**Comment by jomo** [comment]
We could probably use [@barneygale/quarry](https://github.com/barneygale/quarry) which is a python Minecraft protocol implementation and add our token code onto that.

**Comment by jengel3** [comment]
See [Sponge auth server](https://github.com/Jake0oo0/sponge_auth_server), @jomo is working on a database implementation.

**Comment by jengel3** [comment]
1 and 2 are implemented! Will be adding them to a user settings page when I get around to redesigning that :D
