### ISSUE TITLE
Custom Minotar Implementation

### ISSUE THREAD

**Issue by jengel3** [mc-extras/SpongeDev#13]
So, as a side project, I'm considering rewriting the current version of Minotaur to support various other features, especially UUIDs. As of right now, this is the biggest fault of the system, especially considering that name changing is closing in fast.

From what I've figured out so far:

A get request to the URL:  https://sessionserver.mojang.com/session/minecraft/profile/UUID will return a json string with a base64 encoded string, which decodes to a json string (why the fuck is this encoded?) , with output such as:

```
{"timestamp":1413509132177,"profileId":"2d5aa9cdaeb049189930461fc9b91cc5","profileName":"Jake0oo0","textures":{"SKIN":{"url":"http://textures.minecraft.net/texture/a62138178e3f6cd4631a8544403a75b873f1dd1c40be5248da691332977ffeaf"}}}
```

The main thing that is needed from here is the SKIN value, which is the download URL for the skin.

The problem here is making this service just as fast as Minotar (faster please), but also supporting UUIDs, which will require a request to Mojang servers until a username is cached, and then consistently updated since names can change.

I'm trying to decide whether or not this is worth it, but honestly in the long run, it probably is, as Minotar is going to become outdated soon enough.

**Comment by jomo** [comment]
I would actually say we shouldn't _also_ support UUIDs, but rather support UUIDs only.

I've always been wondering why they do the base64 stuff and could never figure out.

Our avatar server would work like this:
- download profile
- extract skin URL
- download skin image
- extract the face
- extract the 2nd layer face
- add the layer to the face
- cache the avatar

I wonder how many browsers support CSS image-rendering. If enough browsers support it, we don't have to handle resizing the avatars as that happens on the client side.

How are we going to cache the avatars?
We can definitely make use of browser caching, too.

How do we extract parts of the original images?
- imagemagick?
- Convert the PNG to a plain bitmap, so they will all have the same size and avatars will always be located at the same position in the byte stream?

What should the server be written in?

**Comment by jengel3** [comment]
I was thinking about the language, any thoughts on that? 

Also, do you have a Skype? If we work on this, it might be best to be able to communicate easier.

**Comment by jomo** [comment]
I don't have Skype, sorry. We can use IRC though.

How about node.js? We also need a name for the thing. Craftheads?

**Comment by jengel3** [comment]
How about Crafatar? Minecraft +  gravatar? :pp

**Comment by jomo** [comment]
:+1:

**Comment by jomo** [comment]
https://github.com/jomo/Crafatar

**Comment by jengel3** [comment]
Web server with @jomo's methods https://github.com/Jake0oo0/crafatar

**Comment by jengel3** [comment]
http://skins.jake0oo0.me/avatars/2d5aa9cdaeb049189930461fc9b91cc5

**Comment by jengel3** [comment]
Closed on behalf of [Crafatar](https://github.com/Jake0oo0/crafatar). A new issue can be open if/when this is ready to be implemented here.

**Comment by jomo** [comment]
"side project"
