### ISSUE TITLE
Create Proper Tests

### ISSUE THREAD

**Issue by jengel3** [mc-extras/SpongeDev#14]
I kinda ignored these to start with...would probably be best to add a testing framework + some simple tests for future reference, and because they're a good idea anyway..

**Comment by jomo** [comment]
I recently worked with [guard](https://github.com/guard/guard#readme). It notices when you change a file and immediately runs tests affected by that change. Quite useful.

[Coveralls](https://coveralls.io/) is probably a good idea, too.

**Comment by jengel3** [comment]
Added rspec + FactoryGirl + shoulda. Should be enough to create basic tests as necessary.
