### ISSUE TITLE
Https support 

### ISSUE THREAD

**Issue by jengel3** [mc-extras/SpongeDev#31]

**Comment by ThunderGemios10** [comment]
You can use CloudFlare: https://cloudflare.com,

They have Free SSL. Using Flexible SSL.

**Comment by jomo** [comment]
He's already using cloudflare for jake0oo0.me. herokuapp.com also has got SSL.
That way we can have full SSL via cloudflare

**Comment by ThunderGemios10** [comment]
@jomo Oh, Then good to know :3

**Comment by jengel3** [comment]
yup, just need to make sure that avatars and such are served as https, and then it just needs to be enabled on cloud flares end.

**Comment by jengel3** [comment]
Completed.
