### ISSUE TITLE
Didn't know where to contact you

### ISSUE THREAD

**Issue by ethsmith** [mc-extras/SpongeDev#37]
Hello I'm the owner of a website dedicated to project hosting for developers and stuff and we are having trouble with making a site for plugin hosting and stuff, I don't know if you are actively working with sponge or this is your own personal project but we would love to add you to our team! :) I would like to make an agreement with you to join us. Please comment back or message me via skype or my websites forums. Skype Name: TekkitCommando97 or Forum Link: http://forums.sourceforums.org/

**Comment by jengel3** [comment]
Hi, I'm not currently associated with the Sponge team, and i created this in my free time. Unfortunately, I don't have the time to work on a similar project, but feel free to use my work with proper credit.

**Comment by ethsmith** [comment]
May I add you on skype although you may not have the time to develop a whole new site like this, you could still join the team. You might actually enjoy it :)

**Comment by ethsmith** [comment]
I understand however thanks for letting me use it as long as I give you proper credit :)

**Comment by jengel3** [comment]
Go ahead, same username as my Github.
