### ISSUE TITLE
MongoDB?

### ISSUE THREAD

**Issue by jengel3** [mc-extras/SpongeDev#9]
Currently using Postgres, but it would probably be best to switch over to Mongoid now that it is not necessary with Forem.

**Comment by jomo** [comment]
What advantages does mongo have over postgres?

**Comment by ThunderGemios10** [comment]
@jomo What he said. Yeah What does Mongo have?

**Comment by jengel3** [comment]
Mongodb supports active record just as Postgres does, but is nosql based, and is much faster in general. Whenever MC auth is implemented, it would be best to be able to use Mongodb on the server end. This is still up for consideration, but I don't see a reason it has to be changed right now.

**Comment by jomo** [comment]
Why is SQL bad? MongoDB is a document store, but this website stores pretty much relational data, so why not use a relational DB like Postgres? (Edit: see also [this question on SO](https://stackoverflow.com/q/5061299/2517068))

I also did a quick [search on Google](https://www.google.com/search?q=%22postgres%22+%22mongodb%22+%22benchmark%22) and it seems like most benchmarks actually show that Postgres is faster / scales better compared to MongoDB.
And why would MC auth be a reason to switch?

I think PostgreSQL would be the better option.
